### ISSUE TITLE
Unable to open application and wrong syntax error for M1 mac on MacOS 15

### ISSUE THREAD

**Issue by gamefreak89** [chessset5/MacOS-TTL-script#1]
I'm on MacOS 15, I'm getting 2 errors when trying to open the application. I'm trying to export the .app file from script editor, but it's giving me a wrong syntax error token on my m1 macbook when trying to export it. 
![Screenshot 2024-09-15 at 2 10 35 PM](https://github.com/user-attachments/assets/715f0c90-20a6-4569-a88e-847bed1ed369)

**Comment by chessset5** [comment]
To verify, you have opened the app in Automator?

**Comment by gamefreak89** [comment]
Yes, I ran it through the automator. I get this error after exporting the app to the applications after opening it. 

<img width="1440" alt="Screenshot 2024-09-15 at 11 42 52 PM" src="https://github.com/user-attachments/assets/bf0471dc-f06a-43c6-8c30-c86300385f30">


\<image two\>

/edited by repository author, removed second image due to sensitive information left by said dumb repo author

**Comment by gamefreak89** [comment]
I have it added to the logins.

edit: It's telling me incorrect username or password. I'm on the current public release of MacOS 15.

**Comment by chessset5** [comment]
Oooooooooh shit, I have my stuff in there. Oops….
Time to remove that….

where it says password “…”, enter your computer’s password in …, make sure it is in “”
e/ let me know if that works and Ill close this issue, I am removing the photo and the app for now until I make a universal fix.

**Comment by gamefreak89** [comment]
Alright, I'll try that when I get home. I'll let you know if it works or not.
